ALTER TABLE refresh_token ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE usuario ADD COLUMN failed_login_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE usuario ADD COLUMN locked_until TIMESTAMPTZ;